######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 3 14:59:40 2015
######################################################################

QT       += core
QT       -= gui

TEMPLATE     = app

TARGET       = CoralSimulationWithDelayAndNoise
DEPENDPATH  += .
INCLUDEPATH += .
CONFIG      += console
CONFIG      -= app_bundle


# Input
SOURCES += CoralSimulationWithDelayAndNoise.ccp.cpp
