######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 3 14:59:40 2015
######################################################################

QT       += core
QT       -= gui

TEMPLATE     = app

TARGET          = CoralSimulationWithDelayAndNoise
QMAKE_CXXFLAGS += -std=c++11 -O3

DEPENDPATH  += .
INCLUDEPATH += .
CONFIG      += console
CONFIG      -= app_bundle


# Input
SOURCES += CoralSimulationWithDelayAndNoise.cpp
